source "https://rubygems.org"

gem 'grape'
gem 'thin'
gem 'rack'
gem 'rack-test'
gem 'exceptions-resource', github: "xdougx/exceptions-resource"

gem 'activesupport'
gem 'actionpack'
gem "mongoid", "~> 4.0.0"
gem 'sprockets', '~> 2.0'

gem 'json'
gem 'jbuilder'

gem 'awesome_print'

gem 'httparty'
gem 'rest-client'


group :development, :test do
  gem 'rerun'
  gem 'rspec'
end